# Generated by Django 3.1.5 on 2021-01-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='excused',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='first_quartile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='median',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='min_score',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='muted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='non_digital_submission',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='posted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='third_quartile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='unlock_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points_possible',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
