# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 3.1.5 on 2021-02-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0002_auto_20210122_1957'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('term', 'week')},
        ),
    ]
