# Generated by Django 3.1.5 on 2021-02-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0002_auto_20210122_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_user_id', models.IntegerField(unique=True)),
                ('login_id', models.TextField(null=True)),
                ('sis_user_id', models.TextField(null=True)),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('full_name', models.TextField(null=True)),
                ('sortable_name', models.TextField(null=True)),
                ('short_name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='student_id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data_aggregator.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data_aggregator.user'),
            preserve_default=False,
        ),
    ]
