# Generated by Django 3.1.6 on 2021-02-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0004_auto_20210218_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='canvas_account_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='canvas_course_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='canvas_user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
