# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 3.1.7 on 2021-04-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0007_auto_20210416_2123'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_assignment',
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('user', 'course', 'assignment_id', 'week'), name='unique_assignment'),
        ),
    ]
