# Generated by Django 3.1.7 on 2021-06-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0008_auto_20210417_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
