# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 3.1.7 on 2021-06-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0009_auto_20210604_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='canvas_term_id',
        ),
    ]
