# Generated by Django 3.2.4 on 2021-07-07 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0010_remove_term_canvas_term_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('subaccount_activity', 'SubAccount Activity')], max_length=80)),
                ('started_date', models.DateTimeField()),
                ('finished_date', models.DateTimeField(null=True)),
                ('term_id', models.CharField(max_length=20)),
                ('term_week', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubaccountActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=20)),
                ('subaccount_id', models.CharField(max_length=100)),
                ('subaccount_name', models.CharField(max_length=200)),
                ('courses', models.PositiveIntegerField(default=0)),
                ('active_courses', models.PositiveIntegerField(default=0)),
                ('ind_study_courses', models.PositiveIntegerField(default=0)),
                ('active_ind_study_courses', models.PositiveIntegerField(default=0)),
                ('xlist_courses', models.PositiveIntegerField(default=0)),
                ('xlist_ind_study_courses', models.PositiveIntegerField(default=0)),
                ('teachers', models.PositiveIntegerField(default=0)),
                ('unique_teachers', models.PositiveIntegerField(default=0)),
                ('students', models.PositiveIntegerField(default=0)),
                ('unique_students', models.PositiveIntegerField(default=0)),
                ('discussion_topics', models.PositiveIntegerField(default=0)),
                ('discussion_replies', models.PositiveIntegerField(default=0)),
                ('media_objects', models.PositiveIntegerField(default=0)),
                ('attachments', models.PositiveIntegerField(default=0)),
                ('assignments', models.PositiveIntegerField(default=0)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('announcements_views', models.PositiveIntegerField(default=0)),
                ('assignments_views', models.PositiveIntegerField(default=0)),
                ('collaborations_views', models.PositiveIntegerField(default=0)),
                ('conferences_views', models.PositiveIntegerField(default=0)),
                ('discussions_views', models.PositiveIntegerField(default=0)),
                ('files_views', models.PositiveIntegerField(default=0)),
                ('general_views', models.PositiveIntegerField(default=0)),
                ('grades_views', models.PositiveIntegerField(default=0)),
                ('groups_views', models.PositiveIntegerField(default=0)),
                ('modules_views', models.PositiveIntegerField(default=0)),
                ('other_views', models.PositiveIntegerField(default=0)),
                ('pages_views', models.PositiveIntegerField(default=0)),
                ('quizzes_views', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_aggregator.report')),
            ],
        ),
    ]
