# Generated by Django 3.2.4 on 2021-07-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0011_report_subaccountactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='type',
            field=models.CharField(choices=[('assignment', 'AssignmentJob'), ('participation', 'ParticipationJob'), ('create_terms', 'CreateTermsJob'), ('create_or_update_courses', 'CreateOrUpdateCoursesJob'), ('create_or_update_users', 'CreateOrUpdateUsersJob'), ('create_assignment_db_view', 'CreateAssignmentDBViewJob'), ('create_participation_db_view', 'CreateParticipationDBViewJob'), ('create_rad_db_view', 'CreateRadDBViewJob'), ('create_rad_data_file', 'CreateRadDataFileJob')], max_length=64),
        ),
    ]
