# Generated by Django 3.2.4 on 2021-07-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0012_alter_jobtype_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='time_tardy',
            new_name='time_total',
        ),
        migrations.AddField(
            model_name='participation',
            name='max_page_views',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='max_participations',
            field=models.IntegerField(null=True),
        ),
    ]
