# Generated by Django 3.2.4 on 2021-08-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0013_auto_20210713_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.NullBooleanField()),
                ('is_dept_adviser', models.NullBooleanField()),
                ('full_name', models.TextField(null=True)),
                ('pronouns', models.TextField(null=True)),
                ('email_address', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
                ('uwnetid', models.TextField(null=True)),
                ('regid', models.TextField(null=True)),
                ('program', models.TextField(null=True)),
                ('booking_url', models.TextField(null=True)),
                ('metadata', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_aggregator.user')),
            ],
        ),
    ]
