# Generated by Django 4.2.11 on 2024-04-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_aggregator', '0015_auto_20210813_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_aggregator.user'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='type',
            field=models.CharField(choices=[('assignment', 'AssignmentJob'), ('participation', 'ParticipationJob'), ('create_terms', 'CreateTermsJob'), ('create_or_update_courses', 'CreateOrUpdateCoursesJob'), ('create_or_update_users', 'CreateOrUpdateUsersJob'), ('create_assignment_db_view', 'CreateAssignmentDBViewJob'), ('create_participation_db_view', 'CreateParticipationDBViewJob'), ('create_rad_db_view', 'CreateRadDBViewJob'), ('create_rad_data_file', 'CreateRadDataFileJob'), ('create_compass_db_view', 'CreateCompassDBViewJob'), ('create_compass_data_file', 'CreateCompassDataFileJob'), ('create_student_categories_data_file', 'CreateStudentCategoriesDataFileJob')], max_length=64),
        ),
    ]
