version: '3.4'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
      AUTH: SAML_MOCK
    restart: always
    container_name: app-canvas-analytics
    build:
      context: .
      target: app-container
    volumes:
      - ./course_data:/app/course_data
    ports:
      - "8000:8000"
