# Generated by Django 3.1.7 on 2021-04-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedCourseSISIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sis_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ManagedCurrentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quarter', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('subaccount_activity', 'SubAccount Activity')], max_length=80)),
                ('started_date', models.DateTimeField()),
                ('finished_date', models.DateTimeField(null=True)),
                ('term_id', models.CharField(max_length=20)),
                ('term_week', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyDataTimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('term', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyDataDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('login_name', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(db_index=True, max_length=500)),
                ('value', models.TextField(null=True)),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.weeklydatatimeperiod')),
            ],
        ),
        migrations.CreateModel(
            name='SubaccountActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=20)),
                ('subaccount_id', models.CharField(max_length=100)),
                ('subaccount_name', models.CharField(max_length=200)),
                ('courses', models.PositiveIntegerField(default=0)),
                ('active_courses', models.PositiveIntegerField(default=0)),
                ('ind_study_courses', models.PositiveIntegerField(default=0)),
                ('active_ind_study_courses', models.PositiveIntegerField(default=0)),
                ('xlist_courses', models.PositiveIntegerField(default=0)),
                ('xlist_ind_study_courses', models.PositiveIntegerField(default=0)),
                ('teachers', models.PositiveIntegerField(default=0)),
                ('unique_teachers', models.PositiveIntegerField(default=0)),
                ('students', models.PositiveIntegerField(default=0)),
                ('unique_students', models.PositiveIntegerField(default=0)),
                ('discussion_topics', models.PositiveIntegerField(default=0)),
                ('discussion_replies', models.PositiveIntegerField(default=0)),
                ('media_objects', models.PositiveIntegerField(default=0)),
                ('attachments', models.PositiveIntegerField(default=0)),
                ('assignments', models.PositiveIntegerField(default=0)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('announcements_views', models.PositiveIntegerField(default=0)),
                ('assignments_views', models.PositiveIntegerField(default=0)),
                ('collaborations_views', models.PositiveIntegerField(default=0)),
                ('conferences_views', models.PositiveIntegerField(default=0)),
                ('discussions_views', models.PositiveIntegerField(default=0)),
                ('files_views', models.PositiveIntegerField(default=0)),
                ('general_views', models.PositiveIntegerField(default=0)),
                ('grades_views', models.PositiveIntegerField(default=0)),
                ('groups_views', models.PositiveIntegerField(default=0)),
                ('modules_views', models.PositiveIntegerField(default=0)),
                ('other_views', models.PositiveIntegerField(default=0)),
                ('pages_views', models.PositiveIntegerField(default=0)),
                ('quizzes_views', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.report')),
            ],
        ),
    ]
