ingress:
  enabled: true
  tls:
    canvas-analytics:
      secretName: test-analytics.apps.canvas.uw.edu-ingress-cert
      hosts:
        - test-analytics.apps.canvas.uw.edu
  hosts:
    canvas-analytics:
      host: test-analytics.apps.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
  podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true
externalService:
  enabled: true
  name: analytics-db-service
  type: ClusterIP
  serviceAddress: 172.18.1.225
  servicePort: 5432
database:
  engine: postgres
  name: canvas_analytics_test
  hostname: analytics-db-service
  secretName: test-analytics.apps.canvas.uw.edu-sql-secrets
repo: canvas-analytics
instance: test
image:
  repository: gcr.io/uwit-mci-axdd/canvas-analytics
  tag: IMAGE_TAG
targetAverageUtilization: 100
resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 50m
    memory: 256Mi
memcached:
  enabled: false
cronjob:
  enabled: true
  jobs:
    - name: add-updt-courses
      schedule: "0 8 * * *" # At 12:00am midnight PST
      command: ["/scripts/management_command.sh"]
      args: ["create_or_update_courses"]
    - name: add-updt-users
      schedule: "0 8 * * *" # At 12:00am midnight PST
      command: ["/scripts/management_command.sh"]
      args: ["create_or_update_users"]
    - name: add-assign-jobs
      schedule: "0 10 * * 6" # At 2:00am PST on Saturday
      command: ["/scripts/management_command.sh"]
      args: ["create_assignment_jobs"]
    - name: add-partic-jobs
      schedule: "0 10 * * 6" # At 2:00am PST on Saturday
      command: ["/scripts/management_command.sh"]
      args: ["create_participation_jobs"]
daemon:
  enabled: true
  daemons:
    - name: run-assign-jobs
      command: ["/scripts/management_daemon.sh"]
      args: ['--cron', '* 12-23 * * 6', 'run_assignment_jobs']
    - name: run-partic-jobs
      command: ["/scripts/management_daemon.sh"]
      args: ['--cron', '* 13-23 * * 6', 'run_participation_jobs']
certs:
  mounted: true
  certPath: /certs/test-apps.canvas.uw.edu-uwca.cert
  keyPath: /certs/test-apps.canvas.uw.edu-uwca.key
  secretName: test-analytics.apps.canvas.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: test

  - name: PWS_ENV
    value: EVAL

  - name: SWS_ENV
    value: EVAL

  - name: CANVAS_ENV
    value: EVAL
  - name: CANVAS_TIMEOUT
    value: "60"

  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test-analytics.apps.canvas.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: test-analytics.apps.canvas.uw.edu

externalSecrets:
  enabled: true
  secrets:
    - name: test-analytics.apps.canvas.uw.edu-canvas-secrets
      externalKey: axdd/kv/data/canvas/shared/secrets
      data:
        - name: canvas-account-id
          property: canvas-account-id

    - name: test-analytics.apps.canvas.uw.edu-secrets
      externalKey: axdd/kv/data/canvas/analytics/test/secrets
      data:
        - name: django-secret
          property: django-secret

    - name: test-analytics.apps.canvas.uw.edu-shared-secrets
      externalKey: axdd/kv/data/canvas/analytics/shared/secrets
      data:
        - name: canvas-api-token
          property: canvas-api-token
        - name: access-group-id
          property: access-group-id

    - name: test-analytics.apps.canvas.uw.edu-sql-secrets
      externalKey: axdd/kv/data/canvas/analytics/shared/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password

    - name: test-analytics.apps.canvas.uw.edu-uwca-certs
      externalKey: axdd/kv/data/canvas/test/uwca-certs
      data:
        - name: test-apps.canvas.uw.edu-uwca.cert
          property: test-apps.canvas.uw.edu-uwca.cert
        - name: test-apps.canvas.uw.edu-uwca.key
          property: test-apps.canvas.uw.edu-uwca.key

    - name: test-analytics.apps.canvas.uw.edu-ic-certs
      externalKey: axdd/kv/data/canvas/analytics/test/ic-certs
      data:
        - name: test-analytics.apps.canvas.uw.edu-ic.cert
          property: test-analytics.apps.canvas.uw.edu-ic.cert

    - name: test-analytics.apps.canvas.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test-analytics.apps.canvas.uw.edu-secrets
    secretKey: django-secret
  canvasAPIToken:
    name: CANVAS_OAUTH_BEARER
    secretName: test-analytics.apps.canvas.uw.edu-shared-secrets
    secretKey: canvas-api-token
  canvasAccountID:
    name: CANVAS_ACCOUNT_ID
    secretName: test-analytics.apps.canvas.uw.edu-canvas-secrets
    secretKey: canvas-account-id
  accessGroup:
    name: ACCESS_GROUP
    secretName: test-analytics.apps.canvas.uw.edu-shared-secrets
    secretKey: access-group-id
  samlSPCert:
    name: SP_CERT
    secretName: test-analytics.apps.canvas.uw.edu-ic-certs
    secretKey: test-analytics.apps.canvas.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test-analytics.apps.canvas.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
