ingress:
  enabled: true
  tls:
    canvas-analytics:
      secretName: test-analytics.canvas.uw.edu-ingress-cert
      hosts:
        - test-analytics.canvas.uw.edu
  hosts:
    canvas-analytics:
      host: test-analytics.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: analytics-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.41
  servicePort: 3306
database:
  engine: mysql
  name: canvas_analytics_test
  hostname: analytics-db-service
  secretName: test-analytics.canvas.uw.edu-sql-secrets
repo: canvas-analytics
instance: test
image:
  repository: gcr.io/uwit-mci-axdd/canvas-analytics
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
cronjob:
  enabled: false
certs:
  mounted: true
  certPath: /certs/test-analytics.canvas.uw.edu-uwca.cert
  keyPath: /certs/test-analytics.canvas.uw.edu-uwca.key
  secretName: test-analytics.canvas.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: test

  - name: WEBSERVER
    value: nginx

  - name: PWS_ENV
    value: EVAL

  - name: SWS_ENV
    value: EVAL

  - name: CANVAS_ENV
    value: EVAL
  - name: CANVAS_TIMEOUT
    value: "60"

  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test-analytics.canvas.uw.edu/saml2
  - name: CLUSTER_CNAME
    value: test-analytics.canvas.uw.edu

externalSecrets:
  enabled: true
  secrets:
    - name: test-analytics.canvas.uw.edu-shared-secrets
      externalKey: axdd/kv/data/canvas/shared/secrets
      data:
        - name: canvas-account-id
          property: canvas-account-id

    - name: test-analytics.canvas.uw.edu-secrets
      externalKey: axdd/kv/data/canvas/analytics/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: canvas-api-token
          property: canvas-api-token

    - name: test-analytics.canvas.uw.edu-sql-secrets
      externalKey: axdd/kv/data/canvas/shared/sql-secrets
      data:
        - name: username
          property: analytics-username
        - name: password
          property: analytics-password

    - name: test-analytics.canvas.uw.edu-uwca-certs
      externalKey: axdd/kv/data/canvas/test/uwca-certs
      data:
        - name: test-apps.canvas.uw.edu-uwca.cert
          property: test-apps.canvas.uw.edu-uwca.cert
        - name: test-apps.canvas.uw.edu-uwca.key
          property: test-apps.canvas.uw.edu-uwca.key

    - name: test-analytics.canvas.uw.edu-ic-certs
      externalKey: axdd/kv/data/canvas/test/ic-certs
      data:
        - name: test-analytics.canvas.uw.edu-ic.cert
          property: test-analytics.canvas.uw.edu-ic.cert

    - name: test-analytics.canvas.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test-analytics.canvas.uw.edu-secrets
    secretKey: django-secret
  canvasAPIToken:
    name: CANVAS_OAUTH_BEARER
    secretName: test-analytics.canvas.uw.edu-shared-secrets
    secretKey: canvas-api-token
  canvasAccountID:
    name: CANVAS_ACCOUNT_ID
    secretName: test-analytics.canvas.uw.edu-shared-secrets
    secretKey: canvas-account-id
  samlSPCert:
    name: SP_CERT
    secretName: test-analytics.canvas.uw.edu-ic-certs
    secretKey: test-analytics.canvas.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test-analytics.canvas.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
